name: Setup Ruby
description: Installs Ruby 3.3 with bundler and its dependency cache for fastlane.

runs:
  using: composite
  steps:
    - name: Setup Ruby
      uses: ruby/setup-ruby@95ef2b042f9d7a56d8268cba8559e2842e2ad01b # v1.321.0
      with:
        ruby-version: "3.3"
        bundler-cache: true
