import { AndroidConfig, type ConfigPlugin } from 'expo/config-plugins';

// Enables Gradle's own local build cache and parallel task execution for
// every Android build produced from this project (Preview, Release, and CI
// verification alike). `android/` is Continuous-Native-Generation output —
// gitignored and regenerated by every `expo prebuild` — so these flags can't
// be hand-written into `android/gradle.properties` directly; a hand edit
// there is silently reverted the next time anything runs `expo prebuild`.
//
// This can't go through `expo-build-properties`'s own plugin config: its
// Android options are a fixed, typed list (`buildArchs`,
// `enableMinifyInReleaseBuilds`, and so on), each wired to one hardcoded
// `gradle.properties` key, with no passthrough for an arbitrary property
// (see `node_modules/expo-build-properties/build/android.js`). Instead this
// plugin is built directly on `expo/config-plugins`' own
// `AndroidConfig.BuildProperties.createBuildGradlePropsConfigPlugin` — the
// exact first-party helper `expo-build-properties` itself is built on — so
// the same regeneration-survival guarantee applies without depending on
// `expo-build-properties` exposing every property this project might ever
// want to set. See
// docs/decisions/2026-08-27-use-expo-build-properties-to-restrict-the-android-abi.md
// for why that same reasoning already led this project to prefer a config
// plugin over a hand edit, and
// docs/operations/preview-deployment.md's "Gradle Build Cache and Parallel
// Execution" section for what these flags do.
//
// `org.gradle.configuration-cache` was tried through this same plugin and
// dropped: enabling it made a real `./gradlew assembleDebug` fail outright,
// with Gradle's own configuration-cache report naming the cause as several
// `node` processes the generated `android/app/build.gradle` (Expo's own
// output, not this plugin) starts at configuration time — e.g.
// `require('expo/scripts/resolveAppEntry')` — which configuration cache does
// not support. See the "Gradle Build Cache and Parallel Execution" section
// of docs/operations/preview-deployment.md for the exact error and why this
// is recorded as an open question rather than forced through.
const withGradlePerformanceProperties: ConfigPlugin<void> =
  AndroidConfig.BuildProperties.createBuildGradlePropsConfigPlugin(
    [
      {
        propName: 'org.gradle.caching',
        propValueGetter: () => 'true',
      },
      {
        propName: 'org.gradle.parallel',
        propValueGetter: () => 'true',
      },
    ],
    'withGradlePerformanceProperties',
  );

export default withGradlePerformanceProperties;
